<?php

/*
 * @file
 * Contains df_tools_content.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function df_tools_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id = 'dcd_import_form') {
    $form['force-update']['#title'] = t('Override existing entities (force-update)');
    $form['force-update']['#description'] = t('The old entity will be deleted and a new entity with the same ID will be created from the imported JSON file.');
    $form['force-update']['#default_value'] = FALSE;
  }

  if ($form_id = 'dcd_export_form') {
    $form['advanced']['tar']['#default_value'] = TRUE;
  }

  if ($form_id = 'dcd_export_entity_form') {
    $form['tar']['#default_value'] = TRUE;
  }
}

/**
 * Implements hook_entity_operation().
 */
function df_tools_content_entity_operation_alter(array &$operations, EntityInterface $entity) {
  // Removes the clone operation from Entity clone for Access unpublished.
  $entityTypeId = $entity->getEntityTypeId();
  if ($entityTypeId == 'access_token') {
    unset($operations['clone']);
  }
}
