<?php

/**
 * @file
 * Contains df_tools_translation_migrate.module.
 */

use Drupal\migrate_source_csv\CSVFileObject;

/**
 * Performs minimum steps necessary to load a CSV from a file.
 *
 * @param string $filename The filename of a CSV
 *
 * @return \Drupal\migrate_source_csv\CSVFileObject The prepared CSV object
 */
function df_tools_translation_migrate_initialize_csv($filename) {
  // Grab the processed CSV file using existing CSV methods.
  $file = new CSVFileObject($filename);
  $file->setHeaderRowCount(1);

  // Map the column names (first row) to values.
  $row = $file->current();
  $column_names = [];
  foreach ($row as $header) {
    $header = trim($header);
    $column_names[] = [$header => $header];
  }
  $file->setColumnNames($column_names);

  return $file;
}
