<?php

/**
 * @file
 * Set up the Article content type for Demo Framework.
 */

/**
 * Implements hook_install().
 */
function df_tools_articles_install() {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  // Enable translation for Articles.
  if (function_exists('df_tools_translation_enable_translation')) {
    df_tools_translation_enable_translation(['node' => ['article']]);
  }
}
