<?php

/**
 * @file
 * Contains df_tools_cohesion.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_toolbar_alter().
 */
function df_tools_cohesion_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'df_tools_cohesion/toolbar';
}

/**
 * Implements hook_entity_operation().
 */
function df_tools_cohesion_entity_operation_alter(array &$operations, EntityInterface $entity) {
  // Removes the clone operation from Entity clone for all Site Studio entity types.
  // Site Studio has a duplicate operation that should be used instead.
  $regex = '/cohesion_*/';
  $entityTypeId = $entity->getEntityTypeId();
  if (preg_match($regex, $entityTypeId)) {
    unset($operations['clone']);
  }
}
