<?php

/**
 * @file
 * Contains df_tools_media_acquiadam.module.
 */

/**
 * Implements hook_modules_installed().
 */
function df_tools_media_acquiadam_modules_installed($modules) {
  $config_factory = \Drupal::configFactory();

  // Adds Acquia DAM to article images.
  if (in_array('df_tools_articles', $modules)) {
    $config_factory
      ->getEditable('field.field.node.article.field_image')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);
  }

  // Adds Acquia DAM to hero images.
  if (in_array('df_tools_blocks', $modules)) {
    $config_factory
      ->getEditable('field.field.block_content.hero.field_hero_background')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);
  }

  // Adds Acquia DAM to event images.
  if (in_array('df_tools_events', $modules)) {
    $config_factory
      ->getEditable('field.field.node.event.field_image')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);
  }

  // Adds Acquia DAM to location images.
  if (in_array('df_tools_locations', $modules)) {
    $config_factory
      ->getEditable('field.field.node.location.field_image')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);
  }

  // Adds Acquia DAM to page images.
  if (in_array('df_tools_page', $modules)) {
    $config_factory
      ->getEditable('field.field.node.page.field_image')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);
  }

  // Adds Acquia DAM to person images.
  if (in_array('df_tools_person', $modules)) {
    $config_factory
      ->getEditable('field.field.node.person.field_image')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);
  }

  // Adds Acquia DAM to product images.
  if (in_array('acf_product', $modules)) {
    $config_factory
      ->getEditable('field.field.node.product.field_product_image')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);

    $config_factory
      ->getEditable('field.field.node.product.field_product_image_more')
      ->set('settings.handler_settings.target_bundles.acquia_dam_asset', 'acquia_dam_asset')
      ->save(TRUE);
  }
}
