sidebar_view_style: titles
image_browser:
  config:
    type: entity_imagebrowser
    dx8_imce_stream_wrapper: public
    dx8_entity_browser: image_browser
  content:
    type: entity_imagebrowser
    dx8_entity_browser: image_browser
